"""Argument parser setup for CycPept3D experiments.

This module builds a single global ``argparse.ArgumentParser`` (``PARSER``)
and registers argument groups for paths, optimizer, training, dataset, and
model options. Other modules import and use this parser to obtain a unified
set of command-line flags.

Notes
-----
- This file intentionally exposes a module-level ``PARSER`` to be imported.
- Argument groups are added by external packages via their ``add_argparse_args``
    class/static methods.
"""

import argparse
import pathlib

from cpmp.model.transformer import CPMPGraphTransformer
from egnn.qm9.models import EGNN
from se3_transformer.se3_transformer.model.transformer import SE3TransformerPooled
from src.dataset import (
    SE3TransformerQM9DataModule,
    SE3TransformerCP3DDataModule,
    CPMPCP3DDataModule,
    EGNNQM9DataModule,
)
from src.utils import str2bool

# Model-specific argparse destination names used elsewhere via getattr(args, name)
# These must match the "dest" generated by argparse for each model's add_argparse_args

COMMON_ARGS = ("seed", "split", "optimizer", "learning_rate", "split", "task")

EGNN_ARGS = (
    "charge_power",
    "in_node_nf",
    "hidden_nf",
    "n_layers",
    "coords_weight",
    "attention",
    "node_attr",
)

CPMP_ARGS = (
    "d_model",
    "N",
    "h",
    "N_dense",
    "lambda_attention",
    "lambda_distance",
    "leaky_relu_slope",
    "dense_output_nonlinearity",
    "distance_matrix_kernel",
    "dropout",
    "aggregation_type",
)

CPMP_CP3D_ARGS = ("pdb", "ig", "wh", "ff")

SE3T_ARGS = (
    "remove_hydrogen",
    "num_layers",
    "num_heads",
    "channels_div",
    "pooling",
    "norm",
    "use_layer_norm",
    "low_memory",
    "num_degrees",
    "num_channels",
)

ARGS_DICT = {
    "se3t": SE3T_ARGS,
    "egnn": EGNN_ARGS,
    "cpmp": CPMP_ARGS,
    "cpmp_cp3d": CPMP_CP3D_ARGS,
}

PARSER = argparse.ArgumentParser(description="CycPept3D")

paths = PARSER.add_argument_group("Paths")
paths.add_argument(
    "--data_dir",
    type=pathlib.Path,
    default=pathlib.Path("data/se3t/Hexene"),
    help="Directory where the data is located or should be downloaded",
)
paths.add_argument(
    "--log_dir",
    type=pathlib.Path,
    default=pathlib.Path("new_results/"),
    help="Directory where the training checkpoints and logs should be saved",
)
paths.add_argument(
    "--load_ckpt_path",
    type=pathlib.Path,
    default=None,
    help="Filename of the checkpoint to be loaded",
)


optimizer = PARSER.add_argument_group("Optimizer")
optimizer.add_argument("--optimizer", choices=["adamw", "sgd"], default="adamw")
optimizer.add_argument(
    "--learning_rate", "--lr", dest="learning_rate", type=float, default=0.002
)
optimizer.add_argument(
    "--min_learning_rate",
    "--min_lr",
    dest="min_learning_rate",
    type=float,
    default=None,
    help="Minimum learning rate during training. If not provided, defaulted to 10% of learning_rate",
)
optimizer.add_argument("--momentum", type=float, default=0.9)
optimizer.add_argument("--weight_decay", type=float, default=0.01)


training = PARSER.add_argument_group("Training")
training.add_argument(
    "--seed",
    type=int,
    default=0,
    help="Set a seed globally. Also use to split the dataset if manual split is not specified.",
)
training.add_argument(
    "--epochs", type=int, default=100, help="Number of training epochs"
)
training.add_argument(
    "--amp",
    type=str2bool,
    nargs="?",
    const=True,
    default=False,
    help="Use Automatic Mixed Precision",
)
training.add_argument(
    "--gradient_clip", type=float, default=None, help="Clipping of the gradient norms"
)
training.add_argument(
    "--accumulate_grad_batches", type=int, default=1, help="Gradient accumulation"
)
training.add_argument(
    "--ckpt_interval", type=int, default=-1, help="Save a checkpoint every N epochs"
)
training.add_argument(
    "--eval_interval",
    dest="eval_interval",
    type=int,
    default=1,
    help="Do an evaluation round every N epochs",
)
training.add_argument(
    "--silent",
    type=str2bool,
    nargs="?",
    const=True,
    default=False,
    help="Minimize stdout output",
)
training.add_argument(
    "--patience",
    type=int,
    default=7,
    help="Early stopping: number of epochs with no significant improvement to wait",
)
training.add_argument(
    "--delta",
    type=float,
    default=0.0001,
    help="Early stopping: minimum change in the monitored metric to qualify as an improvement",
)
training.add_argument(
    "--version",
    type=int,
    default=None,
    help="Run version to be saved. Auto-increment from 0 if not provided. Relevant if resume training from a checkpoint",
)


dataset = PARSER.add_argument_group("Dataset")
dataset.add_argument("--batch_size", type=int, default=256, help="Batch size")
dataset.add_argument(
    "--num_workers", type=int, default=8, help="Number of dataloading workers"
)
dataset.add_argument(
    "--dataset",
    type=str,
    choices=["cp3d", "qm9"],
    default="cp3d",
    help="Dataset to use",
)
dataset.add_argument(
    "--split",
    type=int,
    choices=range(10),
    help="Split of the CP3D dataset to use",
)
dataset.add_argument(
    "--task",
    type=str,
    default="pampa",
    choices=[
        "mu",
        "alpha",
        "homo",
        "lumo",
        "gap",
        "r2",
        "zpve",
        "U0",
        "U",
        "H",
        "G",
        "Cv",
        "U0_atom",
        "U_atom",
        "H_atom",
        "G_atom",
        "A",
        "B",
        "C",
        "pampa",
    ],
    help="Regression task to train on. Only pampa is available for cp3d.",
)


model = PARSER.add_argument_group("Model")
model.add_argument(
    "--model",
    type=str,
    choices=["se3t", "egnn", "cpmp"],
    default="se3t",
    help="Model architecture to use",
)


SE3TransformerPooled.add_argparse_args(PARSER)
CPMPGraphTransformer.add_argparse_args(PARSER)
EGNN.add_argparse_args(PARSER)
SE3TransformerQM9DataModule.add_argparse_args(PARSER)
SE3TransformerCP3DDataModule.add_argparse_args(PARSER)
CPMPCP3DDataModule.add_argparse_args(PARSER)
EGNNQM9DataModule.add_argparse_args(PARSER)
