# -*- coding: utf-8 -*-
"""Scrape CycPeptMPDB.ipynb

Automatically generated by Colab.
"""

# Remember to change the file path when running

import requests
import pandas as pd
import pathlib
from joblib import delayed, Parallel
from tqdm import tqdm

vacuum_dir = pathlib.Path("/content/data/vacuum")
water_dir = pathlib.Path("/content/data/water")
chloroform_dir = pathlib.Path("/content/data/chloroform")

vacuum_dir.mkdir(parents=True, exist_ok=True)
water_dir.mkdir(parents=True, exist_ok=True)
chloroform_dir.mkdir(parents=True, exist_ok=True)

df = pd.read_csv(
    "/content/Random_Split_With_PDB.csv", usecols=["CycPeptMPDB_ID"]
).to_dict(orient="records")
id_list = sorted(record["CycPeptMPDB_ID"] for record in df)

failed_downloads = []


def download_file(idx):
    vacuum_url = f"http://cycpeptmpdb.com/static//peptides/mol/CycPeptMPDB_ID_{idx}.mol"
    water_url = (
        f"http://cycpeptmpdb.com/static//peptides/mol_H2O/CycPeptMPDB_ID_{idx}_H2O.mol"
    )
    chloroform_url = f"http://cycpeptmpdb.com/static//peptides/mol_CHCl3/CycPeptMPDB_ID_{idx}_CHCl3.mol"
    failed = False

    # Download and save vacuum file
    response = requests.get(vacuum_url)
    if response.status_code == 200:
        with open(vacuum_dir / f"CycPeptMPDB_ID_{idx}.mol", "wb") as f:
            f.write(response.content)
    else:
        print(f"Failed to download {vacuum_url}. Status code: {response.status_code}")
        failed = True

    # Download and save water file
    response = requests.get(water_url)
    if response.status_code == 200:
        with open(water_dir / f"CycPeptMPDB_ID_{idx}_H2O.mol", "wb") as f:
            f.write(response.content)
    else:
        print(f"Failed to download {water_url}. Status code: {response.status_code}")
        failed = True

    # Download and save chloroform file
    response = requests.get(chloroform_url)
    if response.status_code == 200:
        with open(chloroform_dir / f"CycPeptMPDB_ID_{idx}_CHCl3.mol", "wb") as f:
            f.write(response.content)
    else:
        print(
            f"Failed to download {chloroform_url}. Status code: {response.status_code}"
        )
        failed = True

    if failed:
        return idx
    else:
        return None


with Parallel(n_jobs=100) as pool:
    results = pool(delayed(download_file)(idx) for idx in tqdm(id_list))

result_set = set(results)

failed_downloads = [idx for idx in id_list if idx not in result_set]

print("IDs that failed to download:")
print(failed_downloads)

len(id_list)

print(f"Number of files in {vacuum_dir}: {len(list(vacuum_dir.iterdir()))}")
print(f"Number of files in {water_dir}: {len(list(water_dir.iterdir()))}")
print(f"Number of files in {chloroform_dir}: {len(list(chloroform_dir.iterdir()))}")

# Colab's specific code to zip and download the files
# !zip -r /content/3d_data.zip /content/data

# from google.colab import files
# files.download("/content/3d_data.zip")
