"""Featurize the dataset once and save to a cache file.

Run this before training to avoid repeating slow PDB/trajectory parsing on
every run. The cache file is a plain torch .pt file containing the featurized
molecule list and atom feature dimension.

For cycpeptmpdb source, ALL trajectory frames from BOTH water and hexane
solvents are stored in a single cache file. Solvent selection (water, hexane,
or both), n_conformers, and rep_frame_only are deferred to training time, so
one cache file works for all modes.

For smiles source, conformers are generated by RDKit using n_conformers from
the config.

Usage:
    # Default config (cycpeptmpdb, both solvents)
    python scripts/featurize.py

    # Explicit output path
    python scripts/featurize.py --output data/my_cache.pt

    # Custom config file
    python scripts/featurize.py --config config/custom.yaml
"""

import argparse
import logging
import pathlib
import sys

import torch
import yaml

_REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT))


def get_args():
    parser = argparse.ArgumentParser(description="Featurize dataset and save cache")
    parser.add_argument(
        "--config",
        default=str(_REPO_ROOT / "config" / "default.yaml"),
    )
    parser.add_argument("--output", type=str, help="Cache output path (.pt)")
    return parser.parse_args()


def main():
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

    args = get_args()

    with open(args.config) as f:
        config = yaml.safe_load(f)

    paths = config["paths"]
    data = config["data"]

    # Resolve output path
    if args.output:
        output = pathlib.Path(args.output)
    elif paths.get("cache_file"):
        output = _REPO_ROOT / paths["cache_file"]
    else:
        source = data["conformer_source"]
        if source == "cycpeptmpdb":
            tag = f"{source}_traj_allframes"
        else:
            tag = f"{source}_allframes"
        output = _REPO_ROOT / "data" / f"cache_{tag}.pt"

    output.parent.mkdir(parents=True, exist_ok=True)

    from src.dataset import featurize_molecules

    molecules, d_atom = featurize_molecules(
        data_dir=_REPO_ROOT / paths["data_dir"],
        csv_path=paths["csv_file"],
        target_col=data["target_col"],
        conformer_source=data["conformer_source"],
        n_conformers=data["n_conformers"],
        pdb_dir=paths.get("pdb_dir"),
        traj_dir=paths.get("traj_dir"),
        ff=data["ff"],
        add_dummy_node=data["add_dummy_node"],
        one_hot_formal_charge=data["one_hot_formal_charge"],
    )

    torch.save({"molecules": molecules, "d_atom": d_atom}, output)
    logging.info(f"Saved {len(molecules)} molecules (d_atom={d_atom}) → {output}")


if __name__ == "__main__":
    main()
